---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u poojamn110729@gmail.com -p Admin@123456 trial2q496n.jfrog.io  
    
    - name: pull an image
      shell: docker pull trial2q496n.jfrog.io/docker-repo/sample_docker_image_with_war_deploy:v1.0-{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 trial2q496n.jfrog.io/docker-repo/sample_docker_image_with_war_deploy:v1.0-{{ build_number }}
 
   
