---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'

  tasks:

  - name: create directory 
    file:
      path: /home/ubuntu/sourcefile
      state: directory
      mode: 0777

  - name: download war file
    ansible.builtin.get_url:
      url: https://trial2q496n.jfrog.io/artifactory/tomcat_app-generic-local/webapp-{{ build_number }}.war
      dest: /home/ubuntu/sourcefile/webapp.war
      username: poojamn110729@gmail.com
      password: Admin@123456

  - name: create directory for backup
    file: 
      path: /home/ubuntu/backup
      state: directory
      mode: 0777

  - name: check if old war exists
    stat:
      path: /opt/tomcat/webapps/webapp.war
    register: war_stat

  - name: backup file with owner and permissions
    copy:
      src: /opt/tomcat/webapps/webapp.war
      dest: /home/ubuntu/backup/webapp.war
      remote_src: yes
   ## when: war_stat.stat.exists   # ✅ only run if the file exists

  - name: Delete remote war file
    file:
      path: /opt/tomcat/webapps/webapp.war
      state: absent

  - name: deploy file with owner and permissions
    copy:
      src: /home/ubuntu/sourcefile/webapp.war
      dest: /opt/tomcat/webapps/webappnew.war
      remote_src: yes
